persistence:
  pg_url: postgresql://vandelay_app:secret@postgres:5432/vandelay
integrations:
  vendors:
    one:
      api_base_url: http://localhost:3060
      auth_path: /auth/%d
      patients_path: /patients
      patient_path: /patients/%d
    two:
      api_base_url: http://localhost:3061
      auth_path: /auth_tokens/%d
      patients_path: /records
      patient_path: /records/%d
