persistence:
  pg_url: postgresql://vandelay_app:secret@postgres:5432/vandelay
integrations:
  vendors:
    one:
      api_base_url: http://mock_api_one:80
    two:
      api_base_url: http://mock_api_two:80
